# -*- coding: utf-8 -*-
"""fi20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MK5IJLhEypyCMDU84UI6Ejp5RXLrCum
"""

!nvidia-smi

!pip install ultralytics

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive

from google.colab import drive
drive.mount('/content/drive')

!ls

!unzip -q /content/drive/MyDrive/20labels.zip -d /content/drive/MyDrive
#!unzip -q /content/drive/MyDrive/yolov8_data/augmented_anno_text.zip -d /content/drive/MyDrive/yolov8_data

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/20 labels
!ls

!yolo task=detect mode=train model=yolov8s.pt data=data.yaml epochs=50  imgsz=640 plots=True

!ls runs/detect/train2/

!pip install pillow
from PIL import Image

from IPython.display import display, Image

image_path = 'runs/detect/train2/confusion_matrix.png'
display(Image(filename=image_path, width=600))

Image(filename='/content/drive/MyDrive/20 labels/runs/detect/train2/val_batch0_pred.jpg',width=600)

# Validation
!yolo task=detect mode=val model=runs/detect/train2/weights/best.pt data=data.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/fu

!yolo task=detect mode=predict model=runs/detect/train2/weights/best.pt conf=0.25 source="/content/drive/MyDrive/img"

from ultralytics.models.yolo import YOLO

model = YOLO("runs/detect/train2/weights/best.pt")
results = model.predict(source='/content/drive/MyDrive/new', save=True, save_txt=True)

